### ISSUE TITLE
Can't truly shutdown connection when using close method

### ISSUE THREAD

**Issue by j78742** [lukeed/sockette#29] opened 2018-06-07 11:47 UTC
In my project, I want to shutdown the connection when I leave out.  However, no matter the code I passed to close method, it failed, e.g. ," ws.close(1000, 'out')". Why?

**Comment by j78742** [comment] 2018-06-07 11:49
The connection shutdown at the time and then reconnected!

**Comment by lukeed** [comment] 2018-06-07 16:02
What do your event hooks look like? Sockette will terminate if it received 1000 or 1005 code. So I'm thinking there's something inside the event hooks that's preventing that.

**Comment by raduciobanu22** [comment] 2018-09-29 14:19
I got the same issue. Calling close() doesn't seem to close the connection.

**Comment by lukeed** [comment] 2018-11-13 22:47
Can you guys try forcing a `1000` code during close?

```js
ws.close(1000)
```

Also, please let me know what browsers & platforms you are/were experiencing this issue.

Thanks!

**Comment by stevesweetney** [comment] 2018-11-14 16:10
I'm experiencing the same issue on firefox in my react app. 
The websocket object closes with code 1006 even when adding 

`ws.close(1000)`

and then it will reconnect.

Also, on 2.0.3 I get unsupported operation error when using the close method

**Comment by lukeed** [comment] 2018-11-14 17:13
Thanks, interesting

Are you at all able to post a snippet or reproduction so that I can dig into it? Would love to squash this lingering issue

**Comment by marcelschulze** [comment] 2019-03-14 21:55
Got the same issue with react-native. It will automatically reconnect. @lukeed Do you have any experience with react native? I could provide a minimal setup to run in the ios simulator.

**Comment by lukeed** [comment] 2019-03-14 22:07
Sure, thank you. I only hear of this issue with RN, so it seems to be specific to that. 

I'll poke thru the repro when you have it :) Thanks

**Comment by marcelschulze** [comment] 2019-04-07 21:04
Sorry for not providing some code... I had a quick look myself right now and it looks like the error code is always 1001, which is not handled in the onclose handler, so it is calling reconnect again. 

` 1001 indicates that an endpoint is "going away", such as a server
  going down or a browser having navigated away from a page.`

1001 is even happening if I do `ws.close(1005)`. Very strange.

**Comment by spereirag** [comment] 2019-04-18 16:13
https://github.com/lukeed/sockette/blob/fb0445cedfc1ff4284c3ddf64ef0e025e8e40467/src/index.js#L20
Line 20 calls reconnect no matter what the error code is. I think it should be:

`(e.code === 1e3 || e.code === 1005) && $.reconnect(e);`

if the intention was to reconnect when a code 1000 or 1005 is received, or 

`!(e.code === 1e3 || e.code === 1005) && $.reconnect(e);`

if the intention was to reconnect when a code other than 1000 or 1005 is received.

**Comment by raduciobanu22** [comment] 2019-05-13 01:02
@lukeed any chance the PR related to this issue gets merged?
Many thanks in advance!

**Closed as completed** 2019-05-13 07:17 UTC
Labels: more info

**Comment by maxime-guyot** [comment] 2019-06-27 09:40
I'have reverse problem. 
With AWS API gateway the connection as gone away after 10 minutes, Sockette receive 1001 code and does not reconnect ... !

**Comment by lukeed** [comment] 2019-06-28 02:40
@maxime-guyot sounds like a keep-alive problem. Clients should be pinging the service on an interval shorter than what the server is configured for, or the load balancer in your case.

1001 means *something* is going away, it doesn't specify client or server. And since every browser will disconnect with a 1001 code when navigating away from the current page, Sockette I can't keep trying to reconnect (since user left)

It's basically a matter of not handling client cleanup correctly versus the server cleaning up idle connections. Sockette can't do both, so it helps out by cleaning up after you and ensuring the client terminates correctly.
